### ISSUE TITLE
Blocking the player 

### ISSUE THREAD

**Issue by Jules-w7** [Jules-w7/Morpion#7]
We're gonna develop 2 new features:

- [x] Blocking the case when it has been clicked to place a caracter inside of it

- [x]  Blocking the player (At least do some prototype)

**Comment by Jules-w7** [comment]
Currently thinking on how we can disable the case to fix the issue #3

**Comment by Jules-w7** [comment]
The case only disable for 1 player but for the other it doesn't disable, we're gonna take a little break and think how we can do this

**Comment by Jules-w7** [comment]
The cells now correctly disable for both player. Check for more on the commit

**Comment by naattch** [comment]
tres drole

**Comment by Jules-w7** [comment]
The blocking system is working well and correctly. Check commit for more.
(thanks to @naattch)
